# EVEN/ODD

In [ ]:
no = 35

if no%2 == 0:
    print("even")
else:
    print("odd")

### <h1>LCM<h1>

In [8]:
a = int(input('first number'))
b = int(input('second number'))

lcm =0

if a>b:
    lcm = a
else:
    lcm = b
while(1): 
    if(lcm%a ==0 and lcm%b==0):
        print('lcm is : ',lcm)
        break
    lcm = lcm+1    
    
    
    
    
    
    
    

first number7
second number21
lcm is :  21


<h1>GCD<h1>

In [9]:
a = int(input('first number'))
b = int(input('second number'))

i=1
hcf=0
while(i<=a and i<=b):
    if(a%i==0 and b%i==0):
        hcf=i
    i=i+1    
        
print(hcf)        

first number20
second number28
4


In [14]:
number = input()

print(len(number))
print(int(number))


433
3
433


<h1>SUM OF ALL DIGITS OF A NUMBER<h1>

In [34]:
no = int(input("enter the no :"))
no = str(no)

l = len(no)
i=0
sumn =0

while(i<l):
    sumn = sumn + int(no[i])
    i = i+1
        
        
print("ans :",sumn)        

enter the no :123
ans : 6


<h1>SUM OF N NUMBERS<h1>

In [53]:
no = int(input('enter the no :'))

i=0
sumn=0
while(i<no+1):
    sumn = sumn + i
    i=i+1
    
print('ans : ',sumn)


enter the no :6
ans :  21


<h1>SUM IN A GIVEN RANGE<h1>

In [57]:
no1 = int(input('enter the no :'))
no2 = int(input('enter the no2 :'))

i=no1
sumn=0
while(i<no2+1):
    sumn = sumn + i
    i=i+1
    
print('ans : ',sumn)

enter the no :3
enter the no2 :6
ans :  18


<h1>FACTORIAL<h1>

In [76]:
no = int(input('enter the no :'))

i =1

prd=1
while(i<no+1):
    prd = prd * i
    i=i+1
    
prd    

enter the no :4


24

<h1>FABBONICCI<h1>

In [95]:

no = int(input('enter the no: '))

i=0
sumn=0
a=0
b=1
while(sumn<=no):
    print('sum is : ',sumn,)
    a=b
    b =sumn
    sumn =a+b
    

enter the no: 10
sum is :  0
sum is :  1
sum is :  1
sum is :  2
sum is :  3
sum is :  5
sum is :  8


# LEAP YEAR

In [95]:
year = int(input('enter the no'))


if year % 4 == 0:
    if year %100 == 0:
        if year %400 ==0:
            print('leap year : ', year)
        else:
            print('not leap year')
    else:
        print("leap year : ",year)
else:
    print("not a leap year")
            
            

enter the no2008
leap year :  2008


# 2D array

In [13]:
import numpy as np

row = int(input('enter the no. of row\n'))
col = int(input('enter the no. col'))

multilist = np.array([[0 for col in range(col)]for row in range(row)])

print(multilist)


for i in range(0,row):
    for j in range(0,col):
        multilist[i][j] = i*j

print('\nafter the calculation','\n\n',multilist)


enter the no. of row
5
enter the no. col8
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

after the calculation 

 [[ 0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7]
 [ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]
 [ 0  4  8 12 16 20 24 28]]


## sort the words

In [ ]:
words = np.array(input('enter the words in CSVs').split(','))

words.sort()

l = len(words)

i=0
newS = ''
while(i<l):
    if newS == '':
        newS = newS+words[i]
        i=i+1
    newS = newS+ ','+words[i]
    i = i+1
    
print('\n',newS)    
    

# delete dupliactes and sort the string

In [ ]:
line = input()

line = line.split(' ')

line = sorted(set(line))

l = len(line)
 
i=0
newSTRING = ''
while(i<l):
    if newSTRING =='':
        newSTRING = newSTRING+line[i]
        i=i+1
    newSTRING = newSTRING+','+line[i]
    i = i+1
    
print('sorted : ',newSTRING)
    


## Question:
Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.
The numbers obtained should be printed in a comma-separated sequence on a single line.

In [116]:

no1 = int(input(''))
no2 = int(input(''))

values = []

for i in range(no1,no2+1):
    s = str(i)
    if (int(s[0])%2==0) and (int(s[1])%2==0) and (int(s[2])%2==0) and (int(s[3])%2==0):
        values.append(s)
        
  


2000
3000


SyntaxError: invalid syntax (<timeit-src>, line 2)

### OPTIMAL WAY  (less than O(logn) )

In [ ]:
no1 = int(input(''))
no2 = int(input(''))

values = []

for i in range(no1,no2+1):
    s = str(i)
    if (int(s[0])%2==0):
        if(int(s[1])%2==0):
            if(int(s[2])%2==0):
                if(int(s[3])%2==0):
                    values.append(s)
            else:
                i = i + 10
        else:
            i = i+100
    else:
        i = i+1000
            
            
values 

### Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.
Suppose the following input is supplied to the program:
9
Then, the output should be:
11106

In [6]:
a = input()
n1 = int( "%s" % a )
n2 = int( "%s%s" % (a,a) )
n3 = int( "%s%s%s" % (a,a,a) )
n4 = int( "%s%s%s%s" % (a,a,a,a) )
print (n1+n2+n3+n4)

9
11106


## password validation check

In [35]:
import re

txt = ''

if ( (len(txt)>=6 and len(txt)<=12) and re.search("[A-Z]",txt) and re.search("[a-z]",txt) and re.search("[0-9]",txt) and re.search("[$#@]",txt)):
    print("valid password")
else:    
    print("invalid password")

invalid password


## Sort a Tuple

In [ ]:
from operator import itemgetter, attrgetter

l=[]

while True:
    s = input('enter the data')
    if not s:
        break
    l.append(tuple(s.split(',')))    

print(sorted(l,key = itemgetter(0,1,2)))    

## divisible by 7

In [41]:
def putNumbers(n):
    i = 0
    while i<n:
        j=i
        i=i+1
        if j%7==0:
            yield j
            
for i in putNumbers(100):
    print(i)           

<generator object putNumbers at 0x000001FDB6A0F780>

In [1]:
i=0
l=[]
n= int(input())
while(i< n):
    if i%7==0:
        l.append(i)
    i=i+1  
    
print(l) 

70
[0, 7, 14, 21, 28, 35, 42, 49, 56, 63]


## Frequency of words

In [1]:
freq = {}
freq1 = {}
line = 'shivam purbia'
for word in line.split():
    freq[word] = freq.get(word,0)+1

words = freq.keys()
sorted(words)

for word in line1.split():
    freq1[word] = freq1.get(word,0)+1

for w in words:
    print ("%s:%d" % (w,freq[w]))

shivam is not a good boy but shivam is boy
shivam:2
is:2
not:1
a:1
good:1
boy:2
but:1


## class example

In [21]:
class Person:
    # Define the class parameter "name"
    name ='person'
    
    def __init__(self, name = None):
        # self.name is the instance parameter
        self.name = name

jeffrey = Person("Jeffrey")
print ("%s name is %s" % (Person.name, jeffrey.name))

nico = Person()
nico.name = "Nico"
print ("%s name is %s" % (Person.name, nico.name))

person name is Jeffrey
person name is Nico


## SQURE table upto N

In [58]:
d = dict()

def printDict(n):
    i=1
    while i<n+1:
        d[i] = i**2
        i=i+1
    print(d)

    

printDict(int(input()))


5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


### STATIC METHOD

In [70]:
class American(object):
    @staticmethod
    def printNationality():
        print("America")

anAmerican = American()
anAmerican.printNationality()
American.printNationality()

America
America


### extract name and company from mail address

In [82]:
mail = 'shivam@google.com'

l=len(mail)
i=0

while(i<l):
    if mail[i] == '@':
        name = mail[:i]
        atpos = i
    if mail[i] == '.':
        company = mail[atpos+1:i]
    i = i+1    

print('Name is : ',name,'\nCompany is : ',company)    

Name is :  shivam 
Company is :  google


### find int in string

In [86]:
import re
s = input()
print(re.findall("\d+",s))

jg7 vhg  7 hvjh 5b  gv 4
['7', '7', '5', '4']


### compress and decompress a string

In [98]:
import zlib
s = 'hello world!hello world!hello world!hello world!'
t = zlib.compress(s)
print(t)
print(zlib.decompress(t))

TypeError: a bytes-like object is required, not 'str'

### Please write a program to print the running time of execution of "1+1" for 100 times.

In [100]:
from timeit import Timer
t = Timer("for i in range(100):1+1")
print(t.timeit())

3.76088127675018


### Question:

With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.

Hints:
Use set() and "&=" to do set intersection operation.

In [119]:
set1=set([1,3,6,24,24,78,35,55])
set2=set([12,24,35,24,88,120,155])
set1 &= set2
li=list(set1)
print(li)

[24, 35]


### Question:Please write a program which prints all permutations of [1,2,3]


Hints:
Use itertools.permutations() to get permutations of list.

In [126]:
import itertools
print(list(itertools.permutations([1,2,3])))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


## Question:Write a program to solve a classic ancient Chinese puzzle: 
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?

Hint:
Use for loop to iterate all possible solutions.


In [131]:
def solve(numheads,numlegs):
    ns='No solutions!'
    for i in range(numheads+1):
        j=numheads-i
        if 2*i+4*j==numlegs:
            return i,j
    return ns,ns

numheads=35
numlegs=94
solutions=solve(numheads,numlegs)
print(solutions)

(23, 12)
